# Generated by Django 5.2.15 on 2026-06-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_am', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Affiliate link',
                'verbose_name_plural': 'Affiliate links (footer)',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_en', models.CharField(blank=True, max_length=80)),
                ('tag_am', models.CharField(blank=True, max_length=80)),
                ('title_en', models.CharField(max_length=300)),
                ('title_am', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField()),
                ('link_url', models.CharField(blank=True, help_text='Internal path or full URL', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage carousel slide',
                'verbose_name_plural': 'Homepage carousel slides',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('climate', 'Climate documents'), ('statistics', 'Statistics documents')], max_length=20)),
                ('title_en', models.CharField(max_length=300)),
                ('title_am', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_am', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents (climate & statistics)',
                'ordering': ['doc_type', 'sort_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label_en', models.CharField(help_text='e.g. Photos from May 19, 2025', max_length=120)),
                ('date_label_am', models.CharField(blank=True, max_length=120)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery album',
                'verbose_name_plural': 'Gallery albums',
                'ordering': ['-event_date', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_am', models.CharField(blank=True, max_length=200)),
                ('role_en', models.CharField(max_length=120)),
                ('role_am', models.CharField(blank=True, max_length=120)),
                ('short_bio_en', models.TextField(blank=True)),
                ('short_bio_am', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('wide_photo', models.BooleanField(default=False, help_text='Use landscape crop on listing card')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leadership profiles',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('climate', 'Climate'), ('economic', 'Economic'), ('policy', 'Policy'), ('demography', 'Demography'), ('social', 'Social'), ('others', 'Others')], max_length=20)),
                ('tag_en', models.CharField(default='News', max_length=80)),
                ('tag_am', models.CharField(blank=True, max_length=80)),
                ('title_en', models.CharField(max_length=300)),
                ('title_am', models.CharField(blank=True, max_length=300)),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_am', models.TextField(blank=True)),
                ('body_en', models.TextField(help_text='Separate paragraphs with a blank line')),
                ('body_am', models.TextField(blank=True, help_text='Separate paragraphs with a blank line')),
                ('image_url', models.URLField()),
                ('published_at', models.DateField()),
                ('search_keywords', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured_home', models.BooleanField(default=False, help_text='Show on homepage news section')),
                ('is_featured_carousel', models.BooleanField(default=False, help_text='Show on homepage hero carousel')),
                ('carousel_tag_en', models.CharField(blank=True, max_length=80)),
                ('carousel_tag_am', models.CharField(blank=True, max_length=80)),
                ('carousel_title_en', models.CharField(blank=True, max_length=300)),
                ('carousel_title_am', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(default='Ministry of Planning and Development', max_length=200)),
                ('site_name_am', models.CharField(blank=True, max_length=200)),
                ('topbar_tag_en', models.CharField(default='Federal Democratic Republic of Ethiopia', max_length=200)),
                ('topbar_tag_am', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(default='011 140 3049', max_length=40)),
                ('email', models.EmailField(default='info@mopd.gov.et', max_length=254)),
                ('address_en', models.CharField(blank=True, default='6 Kilo, Addis Ababa, Ethiopia', max_length=255)),
                ('address_am', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/MoPDETH')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/mopd_ethiopia')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/company/ministry-of-planning-and-development-ethiopia/')),
                ('copyright_text_en', models.CharField(default='© 2026 Ministry of Planning and Development. All rights reserved.', max_length=255)),
                ('copyright_text_am', models.CharField(blank=True, max_length=255)),
                ('footer_desc_en', models.TextField(blank=True)),
                ('footer_desc_am', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SiteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('text_en', models.TextField(blank=True)),
                ('text_am', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, help_text='Admin note only', max_length=200)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations (UI & page copy)',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('alt_am', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_am', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='website.leader')),
            ],
            options={
                'verbose_name': 'Profile paragraph',
                'verbose_name_plural': 'Profile paragraphs',
                'ordering': ['sort_order'],
            },
        ),
    ]
