# Generated by Django 5.2.15 on 2026-06-22 08:57

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, upload_to=website.models.carousel_image_upload),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=website.models.gallery_image_upload),
        ),
        migrations.AddField(
            model_name='leader',
            name='photo',
            field=models.ImageField(blank=True, upload_to=website.models.leader_photo_upload),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to=website.models.news_image_upload),
        ),
    ]
