# Generated by Django 5.2.15 on 2026-06-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_image_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='carousel_tag_am',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='carousel_tag_en',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='carousel_title_am',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='carousel_title_en',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_featured_carousel',
        ),
    ]
