# Generated by Django 5.2.15 on 2026-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_news_carousel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_path',
            field=models.CharField(blank=True, help_text='Original article path on mopd.gov.et', max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='development_plan_pdf_url',
            field=models.URLField(blank=True, default='https://mopd.gov.et/media/ten-year-document/ten_year_development_plan.pdf', help_text='10-Year Development Plan PDF download link'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title_am',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=500),
        ),
    ]
