# Generated by Django 5.2.15 on 2026-06-30 07:07

from django.db import migrations, models


def state_only_addfield(*, model_name, name, field):
    return migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(model_name=model_name, name=name, field=field),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_newsarticle_telegram_notified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['doc_type', 'sort_order', 'title'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents (climate & statistics)'},
        ),
        state_only_addfield(
            model_name='affiliatelink',
            name='name_am',
            field=models.CharField(max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='affiliatelink',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='carouselslide',
            name='tag_am',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        state_only_addfield(
            model_name='carouselslide',
            name='tag_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        state_only_addfield(
            model_name='carouselslide',
            name='title_am',
            field=models.CharField(max_length=300, null=True),
        ),
        state_only_addfield(
            model_name='carouselslide',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        state_only_addfield(
            model_name='document',
            name='description_am',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='document',
            name='title_am',
            field=models.CharField(max_length=300, null=True),
        ),
        state_only_addfield(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        state_only_addfield(
            model_name='galleryalbum',
            name='date_label_am',
            field=models.CharField(help_text='e.g. Photos from May 19, 2025', max_length=120, null=True),
        ),
        state_only_addfield(
            model_name='galleryalbum',
            name='date_label_en',
            field=models.CharField(help_text='e.g. Photos from May 19, 2025', max_length=120, null=True),
        ),
        state_only_addfield(
            model_name='galleryimage',
            name='alt_am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='name_am',
            field=models.CharField(max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='role_am',
            field=models.CharField(max_length=120, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='role_en',
            field=models.CharField(max_length=120, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='short_bio_am',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='leader',
            name='short_bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='leaderparagraph',
            name='text_am',
            field=models.TextField(null=True),
        ),
        state_only_addfield(
            model_name='leaderparagraph',
            name='text_en',
            field=models.TextField(null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='body_am',
            field=models.TextField(help_text='Separate paragraphs with a blank line', null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='body_en',
            field=models.TextField(help_text='Separate paragraphs with a blank line', null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='excerpt_am',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='tag_am',
            field=models.CharField(default='News', max_length=80, null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='tag_en',
            field=models.CharField(default='News', max_length=80, null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='title_am',
            field=models.CharField(max_length=500, null=True),
        ),
        state_only_addfield(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='address_am',
            field=models.CharField(blank=True, default='6 Kilo, Addis Ababa, Ethiopia', max_length=255, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, default='6 Kilo, Addis Ababa, Ethiopia', max_length=255, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='copyright_text_am',
            field=models.CharField(default='© 2026 Ministry of Planning and Development. All rights reserved.', max_length=255, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(default='© 2026 Ministry of Planning and Development. All rights reserved.', max_length=255, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='footer_desc_am',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='footer_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='site_name_am',
            field=models.CharField(default='Ministry of Planning and Development', max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Ministry of Planning and Development', max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='topbar_tag_am',
            field=models.CharField(default='Federal Democratic Republic of Ethiopia', max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='sitesettings',
            name='topbar_tag_en',
            field=models.CharField(default='Federal Democratic Republic of Ethiopia', max_length=200, null=True),
        ),
        state_only_addfield(
            model_name='sitetranslation',
            name='text_am',
            field=models.TextField(blank=True, null=True),
        ),
        state_only_addfield(
            model_name='sitetranslation',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='development_plan_pdf_url',
            field=models.URLField(blank=True, default='/media/ten-year-document/ten_year_development_plan.pdf', help_text='10-Year Development Plan PDF (local /media/ path preferred)'),
        ),
    ]

