# Generated by Django 5.2.15 on 2026-06-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_document_options_affiliatelink_name_am_and_more'),
        ('website', '0019_procurementnotice_closing_date'),
    ]

    operations = [
    ]
