# Generated by Django 5.2.15 on 2026-07-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_merge_20260630_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='development_plan_pdf_url',
            field=models.URLField(blank=True, default='https://mopd.gov.et/media/ten-year-document/ten_year_development_plan.pdf', help_text='10-Year Development Plan PDF download link'),
        ),
    ]
