# Generated by Django 5.2.16 on 2026-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_relax_translation_column_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetranslation',
            name='text',
            field=models.TextField(blank=True, help_text='Plain text only. Press Enter for a new line on supported headings. Do not enter HTML tags.'),
        ),
        migrations.AlterField(
            model_name='sitetranslation',
            name='text_am',
            field=models.TextField(blank=True, help_text='Plain text only. Press Enter for a new line on supported headings. Do not enter HTML tags.', null=True),
        ),
        migrations.AlterField(
            model_name='sitetranslation',
            name='text_en',
            field=models.TextField(blank=True, help_text='Plain text only. Press Enter for a new line on supported headings. Do not enter HTML tags.', null=True),
        ),
    ]
