# Generated by Django 5.2.15 on 2026-07-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_sitetranslation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram channel message id used for inbound sync dedupe', null=True, unique=True),
        ),
    ]
