# Generated by Django 5.2.15 on 2026-08-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_newsarticle_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved comments are shown on the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.newsarticle')),
            ],
            options={
                'verbose_name': 'News comment',
                'verbose_name_plural': 'News comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
