# Generated by Django 5.2.15 on 2026-08-05 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_news_like_count_and_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['created_at'], 'verbose_name': 'News comment', 'verbose_name_plural': 'News comments'},
        ),
        migrations.AddField(
            model_name='newscomment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.newscomment'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Uncheck to hide a comment from the public site.'),
        ),
    ]
