# Generated by Django 5.2.15 on 2026-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_newscomment_parent_likes_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Comments go live immediately. Uncheck only to hide abusive posts.', verbose_name='Visible on site'),
        ),
    ]
