# Generated by Django 5.2.15 on 2026-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_newscomment_visible_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='owner_token',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
