# Generated by Django 5.2.15 on 2026-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_newscomment_owner_edit_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('referrer_host', models.CharField(blank=True, db_index=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page visit',
                'verbose_name_plural': 'Page visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'path'], name='website_pag_created_7404cd_idx'), models.Index(fields=['visitor_key', '-created_at'], name='website_pag_visitor_16064e_idx')],
            },
        ),
    ]
