# Generated by Django 5.2.15 on 2026-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_pagevisit_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='development_plan_pdf_url',
            field=models.URLField(blank=True, default='/media/ten-year-document/ten_year_development_plan.pdf', help_text='10-Year Development Plan PDF download link (prefer local /media/ path)'),
        ),
    ]
